export const colleges = [
  "PSIT Kanpur",
  "Harcourt Butler Technical University (HBTU), Kanpur",
  "Indian Institute of Technology Kanpur (IIT Kanpur)",
  "PSIT College of Higher Education",
  "PSIT Polytechnic",
  "Allenhouse Institute of Technology",
  "Allenhouse Business School",
  "Axis Colleges Kanpur",
  "Kanpur Institute of Technology (KIT)",
  "Maharana Pratap Engineering College",
  "Dr. Ambedkar Institute of Technology for Handicapped",
  "Chhatrapati Shahu Ji Maharaj University (CSJMU)",
  "Rama University Kanpur",
  "University Institute of Engineering and Technology (UIET CSJMU)",
  "Brahmanand Group of Institutions",
  "Pranveer Singh Institute of Technology Pharmacy",
  "Apollo Institute of Technology",
  "BNSD College",
  "DAV College Kanpur",
  "Christ Church College Kanpur",
  "Dayanand Academy of Management Studies",
  "VSSD College",
  "VSICS Kanpur",
  "Seth Sriniwas Agarwal Institute of Engineering & Technology",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT BHU",
  "IIT Indore",
  "IIT Mandi",
  "NIT Trichy",
  "NIT Surathkal",
  "NIT Warangal",
  "NIT Calicut",
  "NIT Allahabad (MNNIT)",
  "NIT Rourkela",
  "NIT Kurukshetra",
  "NIT Jaipur (MNIT)",
  "BITS Pilani",
  "BITS Goa",
  "BITS Hyderabad",
  "IIIT Hyderabad",
  "IIIT Delhi",
  "IIIT Bangalore",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "VIT Vellore",
  "VIT Chennai",
  "SRM Institute of Science and Technology",
  "Manipal Institute of Technology",
  "Thapar Institute of Engineering and Technology",
  "Chandigarh University",
  "Lovely Professional University",
  "KIIT Bhubaneswar",
  "Amity University",
  "Shiv Nadar University",
  "UPES Dehradun",
  "PES University",
  "RV College of Engineering",
  "MS Ramaiah Institute of Technology",
  "BMS College of Engineering",
  "College of Engineering Pune (COEP)",
  "Veermata Jijabai Technological Institute (VJTI)",
  "Anna University",
  "Jadavpur University",
  "Jamia Millia Islamia",
  "Aligarh Muslim University",
  "BHU",
  "Integral University",
  "Graphic Era University",
  "Bennett University",
  "Galgotias University",
  "Galgotias College of Engineering",
  "GLA University",
  "Noida Institute of Engineering and Technology (NIET)",
  "Jaypee Institute of Information Technology",
  "AKGEC",
  "IMS Engineering College",
  "IEM Kolkata",
  "Other",
] as const;
