const ApiError = require("../utils/ApiError");

const hackathons = [
  {
    id: "openai-build-week",
    name: "OpenAI Build Week",
    organizer: "OpenAI",
    domain: "AI",
    mode: "Online",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "21 Jul 2026",
    registrationDeadline: "2026-07-21T17:00:00-07:00",
    eventDates: "13 Jul - 21 Jul 2026",
    location: "Online",
    prizePool: "$100,000 in cash",
    logo: "OA",
    officialWebsite: "https://openai.devpost.com/",
    description:
      "A global week of building with Codex and GPT-5.6 across apps, productivity, developer tools and education.",
    prizeBand: "High",
  },
  {
    id: "pinch-me-i-want-50k",
    name: "Pinch Me! I Want 50K",
    organizer: "Pinch Payments",
    domain: "Data Science",
    mode: "Hybrid",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "22 Jul 2026",
    registrationDeadline: "2026-07-22T17:00:00+10:00",
    eventDates: "23 Jun - 22 Jul 2026",
    location: "Haymarket, Australia",
    prizePool: "$50,000 in cash",
    logo: "PP",
    officialWebsite: "https://devpost.com/submit-to/30520-pinch-me-i-want-50k/manage/submissions",
    description:
      "A nationwide Australian payments and fintech hackathon built around the Pinch Payments API.",
    prizeBand: "High",
  },
  {
    id: "build-with-gemma-nyc",
    name: "Build with Gemma NYC: On-Device AI for Healthcare",
    organizer: "Google DeepMind",
    domain: "AI",
    mode: "Offline",
    status: "Upcoming",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "1 Aug 2026",
    registrationDeadline: "2026-08-01T17:00:00-04:00",
    eventDates: "1 Aug 2026",
    location: "New York City, USA",
    prizePool: "$1,995 in cash",
    logo: "G",
    officialWebsite: "https://gemmanycaihealthcare.devpost.com/",
    description:
      "A one-day hackathon for building privacy-first healthcare tools with Google's open Gemma 4 models.",
    prizeBand: "Medium",
  },
  {
    id: "build-with-gemini-xprize",
    name: "Build with Gemini XPRIZE",
    organizer: "XPRIZE",
    domain: "AI",
    mode: "Online",
    status: "Live",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "17 Aug 2026",
    registrationDeadline: "2026-08-17T13:00:00-07:00",
    eventDates: "19 May - 17 Aug 2026",
    location: "Online",
    prizePool: "$2,000,000 in prizes",
    logo: "GX",
    officialWebsite: "https://xprize.devpost.com/",
    description:
      "A Google Cloud-backed challenge to build a business that operates with AI and ships a working product.",
    prizeBand: "High",
  },
  {
    id: "cockroachdb-aws-agentic-memory",
    name: "CockroachDB x AWS Hackathon - Build with Agentic Memory",
    organizer: "Cockroach Labs",
    domain: "Cloud",
    mode: "Online",
    status: "Live",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "18 Aug 2026",
    registrationDeadline: "2026-08-18T17:00:00-04:00",
    eventDates: "30 Jun - 18 Aug 2026",
    location: "Online",
    prizePool: "$8,750 in cash",
    logo: "CR",
    officialWebsite: "https://cockroachdb-ai.devpost.com/",
    description:
      "An agentic-memory challenge to build on CockroachDB as the persistent memory layer on AWS.",
    prizeBand: "High",
  },
  {
    id: "hacknexus-26",
    name: "HackNexus'26",
    organizer: "Droidecks",
    domain: "AI",
    mode: "Online",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Paid",
    deadline: "20 Jul 2026, 11:56 PM IST",
    registrationDeadline: "2026-07-20T23:56:00+05:30",
    eventDates: "31 Jul - 15 Aug 2026",
    location: "India",
    prizePool: "₹1,00,000 prize pool",
    logo: "HN",
    officialWebsite: "https://unstop.com/hackathons/hacknexus26-droidecks-1695049/amp",
    description:
      "A national-level online hackathon bringing together developers, designers and innovators to solve real-world challenges.",
    prizeBand: "High",
  },
  {
    id: "hackocean-frontend",
    name: "HackOcean - A National Level Frontend Hackathon",
    organizer: "Digital Learning Group and MITS Gwalior",
    domain: "Web Development",
    mode: "Online",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "22 Jul 2026",
    registrationDeadline: "2026-07-22T23:59:00+05:30",
    eventDates: "3 Jul - 24 Jul 2026",
    location: "Gwalior, Madhya Pradesh, India",
    prizePool: "₹1,56,000 prize pool",
    logo: "HO",
    officialWebsite: "https://unstop.com/hackathons/hackocean-a-national-level-frontend-hackathon-madhav-institute-of-technology-and-science-mits-gwalior-1707618/amp",
    description:
      "A national-level online frontend hackathon focused on product thinking, UI/UX and high-quality web experiences.",
    prizeBand: "High",
  },
  {
    id: "hackmatrix-2026",
    name: "HackMatriX 2026 - National Hackathon",
    organizer: "IEEE Computer Society MITS, Gwalior",
    domain: "AI",
    mode: "Online",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "25 Jul 2026, 12:00 AM IST",
    registrationDeadline: "2026-07-25T00:00:00+05:30",
    eventDates: "25 Jul 2026",
    location: "Gwalior, Madhya Pradesh, India",
    prizePool: "₹22,000+ in prizes",
    logo: "HM",
    officialWebsite: "https://unstop.com/hackathons/hackmatrix-2026-24-hour-national-hackathon-ieee-computer-society-mits-gwalior-1701757/amp",
    description:
      "A 24-hour online national hackathon centered on problem solving, innovation and presentation quality.",
    prizeBand: "Medium",
  },
  {
    id: "pec-hacks-4-0",
    name: "PEC HACKS 4.0",
    organizer: "Panimalar Engineering College",
    domain: "AI",
    mode: "Offline",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "22 Jul 2026, 11:59 PM IST",
    registrationDeadline: "2026-07-22T23:59:00+05:30",
    eventDates: "29 Aug - 30 Aug 2026",
    location: "Chennai, Tamil Nadu, India",
    prizePool: "₹1,00,000 top prize; ₹75,000 runner-up; ₹50,000 2nd runner-up",
    logo: "PH",
    officialWebsite: "https://pechacks.org/",
    description:
      "A 36-hour student-led hackathon in Chennai focused on AI, Web3, HealthTech, FinTech, EdTech and open innovation.",
    prizeBand: "High",
  },
  {
    id: "technova-season-3",
    name: "TechNova: Igniting Brilliance (Season 3)",
    organizer: "Enterprise System Solutions Private Limited",
    domain: "Cloud",
    mode: "Hybrid",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Paid",
    deadline: "1 Aug 2026, 10:00 AM IST",
    registrationDeadline: "2026-08-01T10:00:00+05:30",
    eventDates: "1 Aug - 11 Sep 2026",
    location: "Bhubaneswar, Odisha, India",
    prizePool: "₹1,00,000 winner prize; ₹50,000 runner-up",
    logo: "TN",
    officialWebsite: "https://unstop.com/hackathons/technova-igniting-brilliance-season-3-enterprise-system-solutions-private-limited-1709421/amp",
    description:
      "A national tech competition with an online qualifier and an offline championship round in Bhubaneswar.",
    prizeBand: "High",
  },
  {
    id: "hackverse-2026",
    name: "HackVerse 2026 | National Level Innovation Hackathon",
    organizer: "IEEE CIS Student Chapter, Bharati Vidyapeeth Deemed University",
    domain: "Social Impact",
    mode: "Hybrid",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "1 Aug 2026, 12:00 AM IST",
    registrationDeadline: "2026-08-01T00:00:00+05:30",
    eventDates: "8 Jul - 21 Aug 2026",
    location: "Pune, Maharashtra, India",
    prizePool: "Cash prizes, certificates and mentorship",
    logo: "HV",
    officialWebsite: "https://unstop.com/hackathons/hackverse-2026-national-level-innovation-hackathon-bharati-vidyapeeth-deemed-university-1712204/amp",
    description:
      "A national-level innovation hackathon with online rounds and an offline grand finale in Pune.",
    prizeBand: "Medium",
  },
  {
    id: "inceptia-hackathon-2026",
    name: "Inceptia Hackathon 2026",
    organizer: "Pimpri Chinchwad College of Engineering & Research",
    domain: "AI",
    mode: "Hybrid",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Paid",
    deadline: "23 Jul 2026",
    registrationDeadline: "2026-07-23T23:59:00+05:30",
    eventDates: "18 Jul - 8 Aug 2026",
    location: "Pune, Maharashtra, India",
    prizePool: "₹50,000 prize pool",
    logo: "IC",
    officialWebsite: "https://internshala.com/competitions/inceptia/",
    description:
      "A national-level open innovation sprint at PCCOE&R Pune with online ideation and an offline finale.",
    prizeBand: "Medium",
  },
  {
    id: "hacksynergy-2026",
    name: "Hacksynergy 2026",
    organizer: "Inderprastha Engineering College (IPEC), Ghaziabad",
    domain: "Social Impact",
    mode: "Hybrid",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "15 Aug 2026, 12:00 AM IST",
    registrationDeadline: "2026-08-15T00:00:00+05:30",
    eventDates: "11 Jul - 23 Aug 2026",
    location: "Ghaziabad, Uttar Pradesh, India",
    prizePool: "₹1,00,000 prize pool",
    logo: "HS",
    officialWebsite: "https://unstop.com/hackathons/hacksynergy-2026-inderprastha-engineering-college-ipec-ghaziabad-1716413/amp",
    description:
      "A two-stage on-campus hackathon with online ideation and a 24-hour offline finale at IPEC Ghaziabad.",
    prizeBand: "High",
  },
  {
    id: "neuramorphix-hackforge-2026",
    name: "NeuraMorphix HackForge 2026",
    organizer: "Team NeuraMorphix and SRMIST",
    domain: "AI",
    mode: "Online",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "21 Aug 2026, 12:00 AM IST",
    registrationDeadline: "2026-08-21T00:00:00+05:30",
    eventDates: "29 Jun - 20 Sep 2026",
    location: "Chennai, Tamil Nadu, India",
    prizePool: "Prizes and networking opportunities",
    logo: "NM",
    officialWebsite: "https://unstop.com/hackathons/neuramorphix-hackforge-2026-srm-institute-of-science-and-technology-kattankulathur-chennai-1708229/amp",
    description:
      "A 48-hour online hackathon for students focused on AI solutions for real-world problems.",
    prizeBand: "Medium",
  },
  {
    id: "push-to-prod-frontier",
    name: "Push to Prod Hackathon: Building at the Frontier",
    organizer: "Anthropic and Elevation Capital",
    domain: "AI",
    mode: "Offline",
    status: "Upcoming",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "8 Aug 2026",
    registrationDeadline: "2026-08-08T00:00:00+05:30",
    eventDates: "8 Aug 2026",
    location: "Bengaluru, Karnataka, India",
    prizePool: "$10,000 prize pool",
    logo: "PT",
    officialWebsite: "https://pushtoprod-india.devfolio.co/overview",
    description:
      "A one-day in-person hackathon in Bengaluru focused on audacious AI-powered product building.",
    prizeBand: "High",
  },
];

function listHackathons() {
  return hackathons;
}

function getHackathonById(id) {
  const hackathon = hackathons.find((item) => item.id === id);
  if (!hackathon) {
    throw new ApiError(404, "Hackathon not found");
  }
  return hackathon;
}

module.exports = {
  listHackathons,
  getHackathonById,
};
